# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "996db7092826f76edcd3ca70df4e2e01"
name = "tryon-b"
handle = "tryon-b"
application_url = "https://henderson-updating-scanned-generators.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "homezoomzone.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://henderson-updating-scanned-generators.trycloudflare.com/auth/callback",
  "https://henderson-updating-scanned-generators.trycloudflare.com/auth/shopify/callback",
  "https://henderson-updating-scanned-generators.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
