# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d9903a7dadfab136afd8daf849fcf0f6"
name = "try-on-a"
handle = "try-on-a-1"
application_url = "https://show-charged-modern-population.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "homezoomzone.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://show-charged-modern-population.trycloudflare.com/auth/callback",
  "https://show-charged-modern-population.trycloudflare.com/auth/shopify/callback",
  "https://show-charged-modern-population.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
